---

- name: copy conf files
  notify: restart awslogs
  template: src={{ item }}.j2 owner=root dest=/etc/awslogs/{{ item }}
  with_items:
        - awscli.conf
        - awslogs.conf

- name: "copy proxy file"
  template:
    src: proxy.conf.j2
    dest: /etc/awslogs/proxy.conf
    owner: root
    group: root
    mode: 0644
  notify: restart awslogs
  when: awslogs_enable_proxy
