---

- name: Ensure awslogs is installed.
  package:
    name: awslogs
    state: present

- name: Ensure awslogs service is running as configured.
  service:
    name: awslogsd
    state: started
    enabled: yes
